### ISSUE TITLE
请教这个web该如何部署到vercel使用？

### ISSUE THREAD

**Issue by suikaremilia** [lilydjwg/luoxu-web#6]
我通过cloudflare把本地监听的9008端口暴露给了公网，浏览器通过访问https://domian/luoxu/groups可以获取到配置的群组信息。
把web的/src/App.svelte中的
`const LUOXU_URL = "https://tgsearch.kadama.eu.org/luoxu";`
改成了
const LUOXU_URL = "https://domain/luoxu";
之后部署在了vercel。

打开vercel的链接，一直显示正在加载群组信息，其它的都显示正常。
检查后台日志发现报"GET /luoxu/groups HTTP/1.1" 400 177错误

请教下是哪里配错了么？谢谢！

**Comment by lilydjwg** [comment]
你是不是没有配置 luoxu 里的 `web.origins`？这里做了跨站检查。

**Comment by suikaremilia** [comment]
是的，加了域名好了，谢谢！

**Comment by suikaremilia** [comment]
还是不大行，origins加了域以后，可以获取到群组了，然而不能查询，查询报Status code: 500
`TypeError: NetworkError when attempting to fetch resource.`

后台看是模块错误：

```
[E 07-11 08:50:47.452 web_protocol:403] Error handling request
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 433, in _handle_request
        resp = await request_handler(request)
      File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 504, in _handle
        resp = await handler(request)
      File "/opt/tgsearch/luoxu/luoxu/web.py", line 27, in get
        res = await self._get(request)
      File "/opt/tgsearch/luoxu/luoxu/web.py", line 53, in _get
        groupinfo, messages = await self.dbconn.search(q)
      File "/opt/tgsearch/luoxu/luoxu/db.py", line 167, in search
        ret += await self._search_one_year(
      File "/opt/tgsearch/luoxu/luoxu/db.py", line 197, in _search_one_year
        query = text_to_query(q.terms.strip())
      File "/opt/tgsearch/luoxu/luoxu/indexing.py", line 13, in text_to_query
        return querytrans.transform(s)
    AttributeError: module 'querytrans' has no attribute 'transform'
```
感觉不止是跨域错误

**Comment by lilydjwg** [comment]
你编译了 querytrans.so 没有？就是在 querytrans 目录里 `cargo build --release` 一下然后把产物重命名丢到 luoxu 的目录里。

**Comment by suikaremilia** [comment]
我之前已经按readme里说的，进行了编译并重命名到了luoxu的目录里
rustup run nightly cargo build --release
cp libquerytrans.so ../../../querytrans.so

刚又试了下cargo build --release没编译成功……

**Comment by lilydjwg** [comment]
那你试试在 querytrans.so 所在目录开个 python 命令行，然后 `import querytrans` 试试。

**Comment by suikaremilia** [comment]
VPS重置了一下，还是原来的步骤就好了，莫名其妙
谢谢！
